repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: docs/tutorials
      - id: end-of-file-fixer
        exclude_types: [json]
        exclude: docs/tutorials
      - id: debug-statements
        exclude: docs/tutorials

  - repo: https://github.com/PyCQA/isort
    rev: "5.9.3"
    hooks:
      - id: isort
        args: []
        additional_dependencies: [toml]
        exclude: docs/tutorials

  - repo: https://github.com/psf/black
    rev: "21.9b0"
    hooks:
      - id: black
