repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: docs/tutorials
      - id: end-of-file-fixer
        exclude_types: [json]
        exclude: docs/tutorials
      - id: debug-statements
        exclude: docs/tutorials

  - repo: https://github.com/PyCQA/isort
    rev: "5.7.0"
    hooks:
      - id: isort
        args: []
        additional_dependencies: [toml]
        exclude: docs/tutorials

  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black
